[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["DeployVinCask", "VinCask", "VinCaskX"]

[invariant]
runs = 64
depth = 128
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
